### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by NetoSimoes** [Vatsim-Scandinavia/handover#83]
Hello
I'm deploying Handover via docker compose and when I run:
- `docker exec -it --user www-data handover php artisan migrate`
  - Throws this error:
![image](https://github.com/Vatsim-Scandinavia/handover/assets/67044705/aac34861-21f3-4dfc-834e-52652c129466)
- `docker exec -it --user www-data handover php artisan passport:client`
  -  Throws this error: 
![image](https://github.com/Vatsim-Scandinavia/handover/assets/67044705/d394792e-53e7-4790-a4de-b9103a4e9ca4)

I supose migrate would seed the database...

Is something I'm doing incorrectly?

my docker-compose.yml:
```yml
version: '3'

services:
  web:
    container_name: handover
    image: ghcr.io/vatsim-scandinavia/handover:v3
    ports:
        - 8443:443
    volumes:
      - storage:/app/storage
    environment:
      - APP_KEY="I generated the key as per docs"
      - APP_NAME=Passport
      - APP_OWNER="Portugal vACC"
      - APP_OWNER_SHORT=POR
      - APP_OWNER_CONTACT="placeholder@test.org"
      - APP_URL=https://passport.vatsim.pt
      - APP_ENV=production
      - APP_DPP_URL="https://yourvacc.com/link/to/dpp"
      - APP_DPP_DATE="20. February 2020"
      - APP_DPO_MAIL="dpo@yourvacc.com"
      - DB_HOST=localhost
      - DB_DATABASE=passport
      - DB_USERNAME=passport
      - DB_PASSWORD=abcd
      - VATSIM_OAUTH_BASE=https://auth-dev.vatsim.net
      - VATSIM_OAUTH_CLIENT=2121
      - VATSIM_OAUTH_SECRET=efgh
  db:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=passport
      - MYSQL_PASSWORD=abcd
      - MYSQL_DATABASE=passport
    volumes:
      - my-db:/var/lib/mysql
volumes:
  storage:
  my-db:
```

**Comment by blt950** [comment]
Hello, 

The migration will run when you run the supplied commands yes.  Regarding your problem, I believe it's not finding the database. In a docker container setting it could be worth trying '127.0.0.1' in the settings instead of localhost, or finding the docker internal IP if your MySQL instance. Have you tried that?

**Comment by blt950** [comment]
I think it's either the mysql not running or the IP's are wrong or not reachable. Perhaps you have some additional ideas here @thor ?

**Comment by thor** [comment]
Could you elaborate on the steps you run before the commands above, @NetoSimoes?

Plus, please post the output of `docker compose ps` after you get this error.

**Comment by NetoSimoes** [comment]
Got a new error

Sure thing:
- I setup the docker compose on portainer
- Configuration as [above](https://github.com/Vatsim-Scandinavia/handover/issues/83#issue-1977844765)
- Handover has IP 172.28.0.3, db has IP 172.28.0.2
- DB env vars as: [docs](https://hub.docker.com/_/mysql)
  - MYSQL_ROOT_PASSWORD=abcd      
  - MYSQL_PASSWORD=abcd      
  - MYSQL_USER=passport      
  - MYSQL_DATABASE=passport
- Handover db env vars as:
  - DB_HOST=172.28.0.2
  - DB_DATABASE=passport
  - DB_USERNAME=passport
  - DB_PASSWORD=abcd 
- I ran the migrate command as on README `docker exec -it --user www-data handover php artisan migrate`
- I get this last error now ![image](https://github.com/Vatsim-Scandinavia/handover/assets/67044705/4154f891-3991-44c0-862c-8e94486c3583)

**Comment by blt950** [comment]
That last error is progress, you are now able to connect to the database. The issue is most probably that the passport user that you created is not allowed to be connected externally (outside localhost 127.0.0.1). Try configuring your user to allow connections from the outside (as another Docker container would be outside by default)

**Comment by NetoSimoes** [comment]
This last message gave me some ideas.

Got it working!

Final docker-compose.yaml
```yaml
version: '3'

services:
  web:
    container_name: handover
    image: ghcr.io/vatsim-scandinavia/handover:v3
    ports:
        - 8080:80
        - 8443:443
    volumes:
      - handover-storage:/app/storage
    environment:
      - APP_KEY="GENERATED KEY"
      - APP_NAME=Handover
      - APP_OWNER="Your vACC"
      - APP_OWNER_SHORT=XXX
      - APP_OWNER_CONTACT="webmaster@your-vacc.com"
      - APP_URL=https://sub.domain.com
      - APP_ENV=production
      - APP_DPP_URL="https://your-vacc.com/link/to/dpp"
      - APP_DPP_DATE="20. February 2020"
      - APP_DPO_MAIL="dpo@your-vacc.com"
      - DB_HOST=handovermysqldb
      - DB_DATABASE=passport
      - DB_USERNAME=passport
      - DB_PASSWORD=randompassword
      - VATSIM_OAUTH_CLIENT=XXX
      - VATSIM_OAUTH_SECRET=secret

  db:
    container_name: handovermysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: randompassword
      MYSQL_DATABASE: passport
      MYSQL_USER: passport
      MYSQL_PASSWORD: randompassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - handover-db:/var/lib/mysql
volumes:
  handover-storage:
  handover-db:
```
