### ISSUE TITLE
CORS/CSRF token issue when using webclient on different host than handover

### ISSUE THREAD

**Issue by BravoMike99** [Vatsim-Scandinavia/handover#84]
Hello.
 I am unable to perform HTTP requests to the API due to the CORS protocol when using the API through a web page on localhost:4200 and handover on another host/port, This is also the case if I host the handover locally on port 8080 for example.
This is somewhat expected, and I can get around this by disabling web security in the browser itself (--disable-web-security in chrome) but that will trigger a 419 CSRF token mismatch whenever the /oauth/authorize endpoint is used.
Is there any way to disable the CSRF verification or modify the CORS headers for development purposes?

**Comment by NetoSimoes** [comment]
@BravoMike99 Can you share yours steps?
- Deployment
- Endpoints used
- Errors

**Comment by BravoMike99** [comment]
> @BravoMike99 Can you share yours steps?
> 
> * Deployment
> * Endpoints used
> * Errors

Hi,
Handover is deployed as a container on docker using the provided compose file. For database a mysql container is being used.
The web client is an angular application running on localhost 4200.
As far as endpoints goes, this issue applies when attempting to use the /oauth/authorize using a POST request. The errors are the following:
Without --disable-web-security flag:
``
 Access to XMLHttpRequest at 'http://localhost:8080/oauth/authorize?client_id=1&client_secret=XXXXXXXXXXXXXXXXXXXX&response_type=code&redirect_uri=http://localhost:8080/auth/callback&scope=full_name' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 ``
With disable-web-security-flag
``
http status 419 body {"message":"CSRF token mismatch."}
``

**Comment by NetoSimoes** [comment]
Hey @blt950
Do you have any guidance?

**Comment by blt950** [comment]
If I understand you correctly, the CORS/CSRF trigger because both your client and API server is on the same host. If I recall correctly, you could in your local machine `hosts` file add like `handover.test 127.0.0.1` and that way the browser will read `handover.test:8080` as a different server and not triggering the CORS. I've ran into some similar issues, which are the mostly for security reasons by having client and Handover on same localhost domain name when accessing it. 

If that doesn't help, I guess turning to Laravel's CSRF protection config would be a way. I'd go to https://github.com/Vatsim-Scandinavia/handover/blob/main/app/Http/Middleware/VerifyCsrfToken.php#L22C11-L22C11 and add
```
protected $except = [
        //];
```

**Comment by BravoMike99** [comment]
> If I understand you correctly, the CORS/CSRF trigger because both your client and API server is on the same host. If I recall correctly, you could in your local machine `hosts` file add like `handover.test 127.0.0.1` and that way the browser will read `handover.test:8080` as a different server and not triggering the CORS. I've ran into some similar issues, which are the mostly for security reasons by having client and Handover on same localhost domain name when accessing it.
> 
> If that doesn't help, I guess turning to Laravel's CSRF protection config would be a way. I'd go to https://github.com/Vatsim-Scandinavia/handover/blob/main/app/Http/Middleware/VerifyCsrfToken.php#L22C11-L22C11 and add
> 
> ```
> protected $except = ['*'];
> ```
> 
> This should of course ONLY be done for testing purpose, never push that to production.

Hey @blt950, by building the image manually with your suggestion the problem regarding the CSRF is gone, however, I get a 401 ```{"message":"Unauthenticated."}``` when I perform the POST request to the authorized endpoint from my web application. Using postman I get a 200 and the login with vatsim html page. Is there something I could be doing wrong on the browser side or could it be some side effect of having disabled the CSRF & browser security?

**Comment by blt950** [comment]
401's can have many reasons and OAuth2 in general is a bit tricky to debug. I need to see the bigger picture to help out here. If you could elaborate:

- Which web applications are you running, and which http-address do they have
- What is your .env settings on Handover and the application you're connecting with
- What is the Handover client setting for the web application you're trying to connect

I can't help you out about disabling CSRF, it's not a practice I would endorse or know the consequences of. I highly recommend trying out my first point of moving Handover to a non-localhost domain for testing purposes by just letting your `hosts` file redirect a own test domain to Handover instead. Otherwise you'll encounter a lot of CORS issues that I've done as well when I had it on localhost myself. https://www.hostinger.com/tutorials/how-to-edit-hosts-file

**Comment by BravoMike99** [comment]
> 401's can have many reasons and OAuth2 in general is a bit tricky to debug. I need to see the bigger picture to help out here. If you could elaborate:
> 
> * Which web applications are you running, and which http-address do they have
> * What is your .env settings on Handover and the application you're connecting with
> * What is the Handover client setting for the web application you're trying to connect
> 
> I can't help you out about disabling CSRF, it's not a practice I would endorse or know the consequences of. I highly recommend trying out my first point of moving Handover to a non-localhost domain for testing purposes by just letting your `hosts` file redirect a own test domain to Handover instead. Otherwise you'll encounter a lot of CORS issues that I've done as well when I had it on localhost myself. https://www.hostinger.com/tutorials/how-to-edit-hosts-file and add `127.0.0.1 handover.test` or another domain that suits you. Then config the Handover to use that domain in `.env` and try access it in your web browser.

Hi. The hosts file manipulation does not work since from the browser perspective localhost:4200 and localhost:8080 are already different hosts (due to the different port), as such, it fails on the API requests since no CORS headers are present on the laravel/handover side. I've tried changing the host file and using a different request URI the result was the same.
Regarding your other questions
1) Im using an angular application on localhost port 4200 and handover on port 8080. Let's call the angular application A and handover B. Using the angular website I perform an API request to the handover as per the following picture.
![auth](https://github.com/Vatsim-Scandinavia/handover/assets/119708186/751fa5c7-9d54-46f5-84cc-5361345bfbb6)
If I perform the same auth flow using Postman application (https://www.postman.com/)  instead of my local website, I get a 200OK and the login with vatsim webpage.
2) As previously mentioned, I am attempting to connect to handover through the angular website. As far as .env is concered, here goes the .yaml file used to start the container through compose (secrets replaced by XX)
```yaml
version: '3'

services:
  web:
    container_name: handover
    image: handover
    ports:
        - 8080:80
        - 8443:443
    volumes:
      - handover-storage:/app/storage
    environment:
      - APP_NAME=Passport
      - APP_OWNER="Test vACC"
      - APP_OWNER_SHORT=TET
      - APP_OWNER_CONTACT="tech@test-vacc.org"
      - APP_URL=http://localhost:8080
      - APP_ENV=local
      - APP_DPP_URL="https://yourvacc.com/link/to/dpp"
      - APP_DPP_DATE="20. February 2020"
      - APP_DPO_MAIL="dpo@yourvacc.com"
      - APP_KEY="XXX"
      - APP_DEBUG=true
      - DB_HOST=mysqldb
      - DB_DATABASE=passport
      - DB_USERNAME=passport
      - DB_PASSWORD=XXX
      - VATSIM_OAUTH_BASE=https://auth-dev.vatsim.net
      - VATSIM_OAUTH_CLIENT=XXX
      - VATSIM_OAUTH_SECRET=XXXXX

  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XXX
      MYSQL_DATABASE: passport
      MYSQL_USER: passport
      MYSQL_PASSWORD: XXXX
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - handover-db:/var/lib/mysql
volumes:
  handover-storage:
  handover-db:
```
3) Not exactly sure what you mean by this, could you clarify?
